### ISSUE TITLE
Changing orientation in NewCarActivity resets the activity state

### ISSUE THREAD

**Issue by mwiley** [FuelAround/fuel-around-android#4]

**Comment by mwiley** [comment]
[Fixed by 53ddb70](https://github.com/FuelAround/fuel-around-android/commit/53ddb7001a3a24fd02346771f89aacddcbdd0852) in the "mvp" branch (model-view-presenter).

By implementing the MVP architecture pattern, Presenters store the data needed for the activities state and handle business-logic. The fragments and activities create the view layer, and handle any view related logic. They store a reference to the Presenter as a static variable, so it will still exist when the activity is recreated.

https://konmik.github.io/introduction-to-model-view-presenter-on-android.html

**Comment by turtlehump** [comment]
not gunna lie, im kinda pissed off that this continued...

**Comment by mwiley** [comment]
What?

**Comment by turtlehump** [comment]
tyson wont let me do this for a senior project now :(

**Comment by mwiley** [comment]
That sucks dude. If you want to work on it anyway, I can get you up to speed.

**Comment by mwiley** [comment]
Totally fixed the crashing with [b4c9755e](https://github.com/FuelAround/fuel-around-android/commit/b4c9755ef23eef84fa5dfdf70ae62aabeee4b7ab).
